webtalk_init -webtalk_dir C:/Vivado Projects/ECGR 5146/Lab4_RippleCarryAdder/Lab4_RippleCarryAdder.sim/sim_1/behav/xsim/xsim.dir/fullAdderTestbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb  2 22:32:08 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "06b5d457-ea98-452b-a0ae-a42dccfe9d74" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ad521d72e4cf4397a8ff11f2e5823faf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7764_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3893391937 -regid "" -xml C:/Vivado Projects/ECGR 5146/Lab4_RippleCarryAdder/Lab4_RippleCarryAdder.sim/sim_1/behav/xsim/xsim.dir/fullAdderTestbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Vivado Projects/ECGR 5146/Lab4_RippleCarryAdder/Lab4_RippleCarryAdder.sim/sim_1/behav/xsim/xsim.dir/fullAdderTestbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Vivado Projects/ECGR 5146/Lab4_RippleCarryAdder/Lab4_RippleCarryAdder.sim/sim_1/behav/xsim/xsim.dir/fullAdderTestbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
